version: '3'

services:
  api_monitor:
    image: node:alpine
    container_name: setCronTime 
    working_dir: /usr/src/app/setCronTime
    volumes:
      - ./api:/usr/src/app/setCronTime
    ports:
      - 3000:3000
    environment:
        - PORT=3000
    networks:
      - set_crontime
    tty: true
networks:
  set_crontime:
